#!/usr/bin/env bash
set -euo pipefail

R=${R:-100}
METHODS_STR=${METHODS_STR:-"npe rnpe pnpe prnpe rf_abc_npe rf_abc_rnpe"}        # local use only
MEM_GB=${MEM_GB:-12}
NCPUS=${NCPUS:-1}
WALLTIME=${WALLTIME:-"02:00:00"}
PBS_ARRAY_FLAG=${PBS_ARRAY_FLAG:--J}

# Derive counts locally (safe to keep spaces here)
TOT=$(( R * $(wc -w <<<"$METHODS_STR") ))
echo "[launcher] R=$R methods=($METHODS_STR) total=$TOT walltime=$WALLTIME mem=${MEM_GB}GB ncpus=$NCPUS"

qsub ${PBS_ARRAY_FLAG} 0-$((TOT-1)) \
  -N weibull_worker \
  -l walltime="${WALLTIME}",mem="${MEM_GB}GB",ncpus="${NCPUS}" \
  -v R="${R}",METHODS_STR="${METHODS_STR}",OBS_SEED_OFFSET="${OBS_SEED_OFFSET:-1234}",\
N_OBS="${N_OBS:-200}",OBS_MODEL="${OBS_MODEL:-true}",EPS="${EPS:-0.05}",ALPHA="${ALPHA:-40.0}",\
THETA_TRUE="${THETA_TRUE:-0.8}",THETA_TARGET_OVERRIDE="${THETA_TARGET_OVERRIDE:-}",\
LOGK_MU="${LOGK_MU:--0.4}",LOGK_SIGMA="${LOGK_SIGMA:-0.7}",\
LOGLAM_MU="${LOGLAM_MU:-0.7}",LOGLAM_SIGMA="${LOGLAM_SIGMA:-0.7}",\
N_SIMS="${N_SIMS:-20000}",N_POSTERIOR_DRAWS="${N_POSTERIOR_DRAWS:-20000}",\
FLOW_LAYERS="${FLOW_LAYERS:-8}",NN_WIDTH="${NN_WIDTH:-128}",KNOTS="${KNOTS:-10}",INTERVAL="${INTERVAL:-8.0}",\
LEARNING_RATE="${LEARNING_RATE:-5e-4}",MAX_EPOCHS="${MAX_EPOCHS:-500}",MAX_PATIENCE="${MAX_PATIENCE:-10}",BATCH_SIZE="${BATCH_SIZE:-512}",\
Q_PRECOND="${Q_PRECOND:-0.2}",SMC_N_PARTICLES="${SMC_N_PARTICLES:-4000}",SMC_ALPHA="${SMC_ALPHA:-0.5}",SMC_EPSILON0="${SMC_EPSILON0:-1e6}",\
SMC_EPS_MIN="${SMC_EPS_MIN:-1e-3}",SMC_ACC_MIN="${SMC_ACC_MIN:-0.10}",SMC_MAX_ITERS="${SMC_MAX_ITERS:-4}",\
SMC_INITIAL_R="${SMC_INITIAL_R:-1}",SMC_C_TUNING="${SMC_C_TUNING:-0.01}",SMC_B_SIM="${SMC_B_SIM:-1}",\
DENOISE_MODEL="${DENOISE_MODEL:-spike_slab}",LAPLACE_ALPHA="${LAPLACE_ALPHA:-0.3}",LAPLACE_MIN_SCALE="${LAPLACE_MIN_SCALE:-0.01}",\
STUDENT_T_SCALE="${STUDENT_T_SCALE:-0.05}",STUDENT_T_DF="${STUDENT_T_DF:-1.0}",CAUCHY_SCALE="${CAUCHY_SCALE:-0.05}",\
SPIKE_STD="${SPIKE_STD:-0.01}",SLAB_SCALE="${SLAB_SCALE:-0.25}",MISSPECIFIED_PROB="${MISSPECIFIED_PROB:-0.33}",\
LEARN_PROB="${LEARN_PROB:-1}",MCMC_WARMUP="${MCMC_WARMUP:-1000}",MCMC_SAMPLES="${MCMC_SAMPLES:-2000}",MCMC_THIN="${MCMC_THIN:-1}" \
  jobs/weibull_worker.pbs
